name: Release AddOn

#on: [push]
on:
  push:
    branches:
      - master
    tags:
      - '**'
  workflow_dispatch:


jobs:
#  full_package_release:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0

#      - uses: BigWigsMods/packager@v2

  standalone_release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package and release
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Details
          path: /Details*.zip
