name: Sync fork

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
    
  sync:
    runs-on: ubuntu-latest

    steps:

      - name: Fork-sync
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: Tercioo
          base: master
          head: master
