name: Tag Workflow

on: 
  pull_request_target:
    types:
      - closed
  workflow_dispatch:

  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Tag name
        id: tag_name
        run: |
          echo "RELEASE_TAG=v$(date +'%y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.tag_name.outputs.RELEASE_TAG }}
          tag_exists_error: false
          message: "Latest release"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.tag_name.outputs.RELEASE_TAG }}
          release_name: Release ${{ steps.tag_name.outputs.RELEASE_TAG }}
          body: |
            automated release with upstream updates
          draft: false
          prerelease: false
