name: Tag Workflow

on:
  workflow_run:
    workflows: [Scheduled merge action, Manual Merge Remote Action]
    types: completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: |
          echo "::set-output name=name::$(date +'%Y-%m-%d-%H-%M')"
          echo "::set-output name=tag::$(date +'%Y%m%d%H%M')"
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        title: "${{ steps.date.outputs.name }}"
        tag: "release-${{ steps.date.outputs.tag }}"
